name: pomsky-server
region: fra
services:
- envs:
  - key: ROCKET_ADDRESS
    scope: RUN_TIME
    value: 0.0.0.0
  http_port: 8000
  image:
    registry_type: DOCR
    repository: pomsky-server
    tag: latest
  instance_count: 1
  instance_size_slug: basic-xxs
  name: server
  routes:
  - path: /
  run_command: pomsky-server
